### ISSUE TITLE
Hombrew support

### ISSUE THREAD

**Issue by mitchellmaler** [kubie-org/kubie#12]
Hello,

Would it be possible to add a homebrew formula when you release versions of this application? Would allow installing and updating to be easy for users.

**Comment by sbstp** [comment]
It would certainly be possible. I have no experience with homebrew however. Should the formula be committed to their repo?

**Comment by caalberts** [comment]
No it doesn’t need to be committed to their repo. You can use `brew tap` for that. https://docs.brew.sh/Taps. The formula will be committed to your repo, something like `sbstp/homebrew-tap`.

**Comment by c10l** [comment]
I have submitted a PR on homebrew-core: https://github.com/Homebrew/homebrew-core/pull/52502

**Comment by sbstp** [comment]
Thanks! This is great!

**Comment by jjuarez** [comment]
Meanwhile, you can install the formula using my tap, which installs the 0.9.1 version for now
```bash
brew tap jjuarez/tap
brew install kubie
```

**Comment by c10l** [comment]
The pull request has been merged to `homebrew-core`. This issue can be closed now. :)
