### ISSUE TITLE
Feature Request: Use Github releases

### ISSUE THREAD

**Issue by johnhamelink** [kubie-org/kubie#15]
Hi there,

I was interested in building a plugin for [asdf][0], but I noticed that the rust binaries are rather awkwardly kept in the git repository itself.

It would be much nicer if instead they were deployed to the github releases section. This would allow me to use Github's API to produce a list of version numbers and to install binaries.

[0]: https://github.com/asdf-vm/asdf

**Comment by sbstp** [comment]
This is in the plans! It's the next thing I'm working on. They were in the repo at first because I pushed it to a bunch of repos and I wanted it to be git platform independent.

**Comment by johnhamelink** [comment]
Sweet! That's excellent, thanks :D

**Comment by sbstp** [comment]
Hey! I've just finished doing this. Everything looks good, I had a friend test the OS X binary. There's two binaries per release, one named `kubie-linux-amd64` and one named `kubie-darwin-amd64`.

**Comment by sbstp** [comment]
Please let me know if there's issues.

**Comment by pxtxs** [comment]
All good on my side for the OSX release

**Comment by sbstp** [comment]
I'm going to close this, let me know if there's issues.

**Comment by johnhamelink** [comment]
I've built the asdf integration, which you can check out [here][0] and [here][1].

[0]: https://github.com/johnhamelink/asdf-kubie
[1]: https://github.com/asdf-vm/asdf-plugins/pull/223

Thanks for your help! :)
