### ISSUE TITLE
Fish support

### ISSUE THREAD

**Issue by mazzy89** [kubie-org/kubie#17]
It would be possible to usee Fish as a subshell?

**Comment by sbstp** [comment]
Yes absolutely. It's one of the things I mentioned in the blog post (future plans). I found out yesterday that recent OSX versions default to `zsh` now, so this is the priority for me at the moment but I'll work on fish after.

**Comment by ghost** [comment]
Please make this happen. I love kubie but it's not working properly with Fish. Works great with ZSH but Fish is awesome so I want to use Fish. Thanks for the awesome tool.
