### ISSUE TITLE
kubie: error while loading shared libraries: libssl.so.1.0.0

### ISSUE THREAD

**Issue by mhaluska** [kubie-org/kubie#24]
kubie version: 0.8.1
os: debian 10
openssl:
```
$ dpkg -l | grep libssl
ii  libssl1.1:amd64                      1.1.1d-0+deb10u2                   amd64        Secure Sockets Layer toolkit - shared libraries
```
error:
```
$ kubie --help
kubie: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by mhaluska** [comment]
```
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
$ kubie -V
kubie: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

```
$ sudo ln -sf /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
$ kubie -V
kubie: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by kubie)
kubie: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by kubie)
kubie: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found (required by kubie)
kubie: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by kubie)
```

**Comment by luna-duclos** [comment]
Getting the same issue on debian

**Comment by pxtxs** [comment]
As a temp-fix, you can build from source to have a binary dynamically linked to the right libraries.
`cargo install kubie` should be enough if you already have a rust setup 👍

**Comment by sbstp** [comment]
This is caused by the fact that we have added attohttpc, which uses native-tls. If you want to build `kubie` you need to install `libssl-dev` now.

It seems like you are having this issue just using the binary though, not building it, which is strange. I'll investigate what's going on and get back to you.

I run Debian 10 on my machine and it works fine. In the mean time you can probably install libssl-dev and it will work. `apt-get install libssl-dev`

**Comment by sbstp** [comment]
I think it might be due to the travis-ci pipelines running on a rather old Ubuntu, 16.04. The latest version of OpenSSL is 1.1, not 1.0.

I can either force travis to use a more recent version of Ubuntu, or use attohttpc's rustls feature to use something that doesn't depend at all on OpenSSL.

**Comment by pxtxs** [comment]
Both are working on my side because I have both openssl 1.0 and 1.1 installed.
```
$ ldd kubie
	linux-vdso.so.1 (0x00007ffdbb484000)
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f228a3cb000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f228a0fa000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f228a0f5000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f228a0d3000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f228a0b9000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f2289ef2000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f228ac54000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f2289daa000)
$ ldd downloaded-kubie 
ldd: warning: you do not have execution permission for `./downloaded-kubie'
	linux-vdso.so.1 (0x00007ffda4fe6000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007f0fdd1ee000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007f0fdcf7c000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f0fdcf77000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f0fdcf6c000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f0fdcf4a000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f0fdcf30000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f0fdcd67000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f0fdd6be000)
```

Is there any option to use a static openssl ?

**Comment by sbstp** [comment]
Yes! https://docs.rs/native-tls/0.2.4/native_tls/#cargo-features

**Comment by pxtxs** [comment]
Nice, I also found this discussion : https://users.rust-lang.org/t/how-to-link-openssl-statically/14912/16
Looks like the same issue.

My PR introduced this bug :/ I can investigate more after my work day if you want.

**Comment by sbstp** [comment]
I've pushed a [commit](https://github.com/sbstp/kubie/commit/e3c8e6608fc9e8ef2da7a91625fdf9f71493fcfe) which removes the dependency on OpenSSL. I will create a new release in a few minutes.

**Comment by sbstp** [comment]
Can you try the binary for [0.8.2](https://github.com/sbstp/kubie/releases/tag/v0.8.2)? There should not be a dependency on OpenSSL anymore.

**Comment by pxtxs** [comment]
LGTM

```
$ ldd kubie
	linux-vdso.so.1 (0x00007ffdc5fdb000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f3904d68000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f3904d5d000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f3904d3b000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3904d21000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f3904b5a000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f39052ac000)
```

**Comment by mhaluska** [comment]
Works like a charm, thank you.
