### ISSUE TITLE
libssl.so.1.0.0: cannot open shared object file

### ISSUE THREAD

**Issue by ghost** [kubie-org/kubie#26]
I get error below when using Kubie on Archlinux. I found that Arch have `libssl.so.1.1` but not `libssl.so.1.0.0` and there seems to be no way to install that version. Can this be fixed? I really like Kubie. Thanks.

`kubie: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

**Comment by ghost** [comment]
Found out that you had to install `openssl-1.0` manually on Arch for this to work. Full command below.

`sudo pacman -S openssl-1.0`

**Comment by sbstp** [comment]
FYI this issue has also been reported in #24, and it's being fixed as we speak. We will remove all dependencies on OpenSSL.
