### ISSUE TITLE
Feature Request: Allow importing custom PS1 config for use while in context

### ISSUE THREAD

**Issue by dirtycajunrice** [kubie-org/kubie#29]
Subshell ps1 config would allow an extra layer of configuration.

**Comment by sbstp** [comment]
How would you like this to be done? Do you want to be able to customize the prompt via kubie's config file or do you want kubie to allow you to overwrite the prompt via some sort of hook?

**Comment by dirtycajunrice** [comment]
My initial attempt was to only enable some of my ps1 when one of the kubie env vars was set since it spawns a new shell. From what i can tell, your bashrc is loaded prior to kubie config therefore it doesnt do any good. 

Low hanging fruit would be allowing a source to a file post init i think? Thoughts?

**Comment by sbstp** [comment]
Are you using bash on a Mac machine? There's currently a bug in how the bash config files are loaded on Mac, see #13

**Comment by dirtycajunrice** [comment]
I am on ubuntu 19.10 and do not have that issue :D

**Comment by sbstp** [comment]
Can you give me more details about you want to achieve exactly? I'm not sure I understand fully what you want to do.

**Comment by dirtycajunrice** [comment]
I actually got it working. Thanks for your patience. For those reading later that use kube-ps1 still with kubie, here is an example of using kubie's `KUBIE_ACTIVE` var to trigger visibility only when in a kubie ctx:
```
if [ ! -z ${KUBIE_ACTIVE+x} ]
then
    # PS1 Pre-bash-git
    source ~/.kube-ps1/kube-ps1.sh
    PS1_PREFIX='\u@\h $(kube_ps1)$(aws_prompt)'
else
    PS1_PREFIX='\u@\h$(aws_prompt)'
fi
PS1_SUFFIX='\n\[\033[0;33m\]\w\[\033[0;0m\] \$ '
PS1="${PS1_PREFIX}${PS1_SUFFIX}"
```
