### ISSUE TITLE
Kubie not using KUBECONFIG environment variable

### ISSUE THREAD

**Issue by ghost** [kubie-org/kubie#41]
I exported `KUBECONFIG` as env var but kubie doesn't use it. It kept saying `Error: Not in a kubie shell!` when I do `kubie ns`. Here are my steps.

1. `export KUBECONFIG=$HOME/.kube/kind`
2. `kubie ns`

Error above thrown.

**Comment by sbstp** [comment]
Try `kubie ctx -f ~/.kube/kind` which was just released in `0.9.0`. You need to enter a context before you can switch namespace.
