### ISSUE TITLE
Deleting current namespace will leave context unusable

### ISSUE THREAD

**Issue by jnatten** [kubie-org/kubie#44]
Running `kubie 0.9.0` on archlinux (5.6.10)

Steps to reproduce:
1. 
```
$ kubie ctx test
$ kubie ns newns
```
2. I did it in another shell, but not sure if that matters.
```
$ kubectl delete ns newns
```

Now one cant switch to that context anymore:
```
$ kubie ctx test
Error: 'newns' is not a valid namespace for the context
```

**Comment by sbstp** [comment]
Hi! I figured this might happen but I did not think it was likely to. Should be fixable.

**Comment by sbstp** [comment]
Just to be clear on what's going on: in 0.9.0 I added a namespace history feature which keeps the last namespace used for each context. When you enter it reads the last one from the history file. To fix the issue you can either edit the history file (it's JSON) or remove it. 

`vim $KUBIE_STATE` or `rm $KUBIE_STATE` (will remove history for other contexts)

**Comment by sbstp** [comment]
If you don't have a shell open the state file is in `~/.local/share/kubie/state.json`

**Comment by jnatten** [comment]
> Hi! I figured this might happen but I did not think it was likely to. Should be fixable.

To be fair it isn't a very regular occurrence, it was just a bit annoying, especially since it took me some time to find the state file (I forgot my search tool required a `--hidden` flag :facepalm:).

I could take a look at making a PR with a fix if you would like, but I'm not very proficient in rust.

**Comment by sbstp** [comment]
It's a pretty easy thing to fix, I should have time to do it soon.

**Comment by sbstp** [comment]
https://github.com/sbstp/kubie/commit/8d6af9e851b67ae8c35d155acb12396627d9b0a7 should fix the issue

**Comment by sbstp** [comment]
I will release 0.9.1
