### ISSUE TITLE
Support alpine resp. musl or link it statically

### ISSUE THREAD

**Issue by mkilchhofer** [kubie-org/kubie#55]
I tried to run `kubie` (v0.11.1) on my alpine based jumphost and it doesn't work.
On my fedora and ubuntu based workstations it works well.

Maybe it would be a good idea to statically link all needed stuff as kubectl, helm and so on are all statically linked.
Here's the output of `ldd`:

```console
$ ldd bin/kubie-linux-amd64 
	/lib64/ld-linux-x86-64.so.2 (0x7f7695b61000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f7695657000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f7695b61000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f7695b61000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f7695b61000)
Error relocating bin/kubie-linux-amd64: __res_init: symbol not found
Error relocating bin/kubie-linux-amd64: __register_atfork: symbol not found
```

**Comment by sbstp** [comment]
Yeah by default Rust depends on libc, I build it in a Ubuntu environment I think, so it would use glibc. I'll see what can be done about this.

**Comment by sbstp** [comment]
Looks simple enough https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html

**Comment by sbstp** [comment]
Hey! I've been meaning to switch to Github Actions for a while, so this was the perfect opportunity. I've released 0.12.0 which is built fully statically with musl. Can you try it out and let me know if it works for you? `ldd` does not return anything :)

**Comment by mkilchhofer** [comment]
Wow, that was fast! :partying_face: 
Indeed kubie now works perfectly on my alpine 3.12 jumphost. :+1: 

`ldd` now returns, that kubie isn't a dynamic program anymore:
```console
$ ldd bin/kubie
/lib/ld-musl-x86_64.so.1: bin/kubie: Not a valid dynamic program
```
I hope it's okay for you when I close this now? :-)

**Comment by sbstp** [comment]
Yep :)
