### ISSUE TITLE
kubie exec command provides no error message if context is not setup

### ISSUE THREAD

**Issue by SEANDOUGHTY** [kubie-org/kubie#63]
For example if you run `kubie exec random random echo random` there will be shell output informing the user that the context does not exist.

This would be a nice QoL improvement for debugging scripts that use the `kubie exec` command.

**Comment by sbstp** [comment]
Hey thanks for reporting this! We'll have a fix for this in the next week or so.

**Comment by sbstp** [comment]
Hey Sean, the issue is fixed and I've released kubie `0.13.2` for monday.

**Comment by SEANDOUGHTY** [comment]
Hey Simon! Thanks so much for addressing this.
