### ISSUE TITLE
No homebrew aarch64 (Apple Silicon) bottle

### ISSUE THREAD

**Issue by muuvmuuv** [kubie-org/kubie#64]
Trying our company's k8 on my M1 at the moment and would love to use kubie. Does it already has a release binary for aarch64? And can we get the homebrew bottle updated to easily install it?

**Comment by sbstp** [comment]
I publish a macos arm64 build in the releases https://github.com/sbstp/kubie/releases

**Comment by muuvmuuv** [comment]
Overseen it, thanks, that works! Still, the homebrew bottle is missing, so I would keep that open.

**Comment by sbstp** [comment]
I'm not maintaining the homebrew stuff, you should probably ask for it in the homebrew repo.
