### ISSUE TITLE
Feature Suggestion: Print context names when using `kubie exec` with wildcard

### ISSUE THREAD

**Issue by TyBrown** [kubie-org/kubie#71]
Hey @sbstp ... What are your thoughts on this idea? I'm happy to submit a PR if you'll accept, figured we could chat about it here first.

Currently, we've got 10 contexts at work, and I've been trying to get used to using `kubie exec *` to run commands across all of the contexts, however, I'm running into some trouble with understanding which resources are coming from which cluster/context.

Example from kubie 0.13.4:
```
$ kubie exec *-admin default kubectl get scaledobject -o wide --all-namespaces
NAMESPACE    NAME            SCALETARGETKIND      SCALETARGETNAME     MIN   MAX   TRIGGERS        AUTHENTICATION   READY   ACTIVE   AGE
monitoring   sqs-queue-foo   apps/v1.Deployment   foo-app             0     1     aws-sqs-queue                    True    False    9d
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
NAMESPACE    NAME            SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS        AUTHENTICATION   READY   ACTIVE   AGE
monitoring   sqs-queue-foo   apps/v1.Deployment   foo-app           0     1     aws-sqs-queue                    True    False    9d
NAMESPACE    NAME            SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS        AUTHENTICATION   READY   ACTIVE   AGE
monitoring   sqs-queue-foo   apps/v1.Deployment   foo-app           0     1     aws-sqs-queue                    True    False    9d
No resources found
```

As you see, it's hard to know which resources are from which cluster/context.

I'd like to propose something like:
```
$ kubie exec *-admin default kubectl get scaledobject -o wide --all-namespaces
CONTEXT => dev-admin
NAMESPACE    NAME            SCALETARGETKIND      SCALETARGETNAME     MIN   MAX   TRIGGERS        AUTHENTICATION   READY   ACTIVE   AGE
monitoring   sqs-queue-foo   apps/v1.Deployment   foo-app             0     1     aws-sqs-queue                    True    False    9d

CONTEXT => mno-dev-admin
No resources found

CONTEXT => mno-prd-admin
No resources found

CONTEXT => mno-stg-admin
No resources found

CONTEXT => pqr-dev-admin
No resources found

CONTEXT => pqr-prd-admin
No resources found

CONTEXT => pqr-stg-admin
No resources found

CONTEXT => prd-admin
NAMESPACE    NAME            SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS        AUTHENTICATION   READY   ACTIVE   AGE
monitoring   sqs-queue-foo   apps/v1.Deployment   foo-app           0     1     aws-sqs-queue                    True    False    9d

CONTEXT => stg-admin
NAMESPACE    NAME            SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS        AUTHENTICATION   READY   ACTIVE   AGE
monitoring   sqs-queue-foo   apps/v1.Deployment   foo-app           0     1     aws-sqs-queue                    True    False    9d

CONTEXT => svc-admin
No resources found
```

I'm not set on the specific format... and I think having a flag option to disable it would be useful (or perhaps the other way around, though I think a better UX would be to print the context info by default). Let me know what you think about this one.

Still loving Kubie, slowly convincing my co-workers that it's awesome too!

Cheers,
Ty

**Comment by sbstp** [comment]
Yeah it's a good idea, I've thought about it but I didn't want to mix the outputs together.

I think what we could do is print the context name if stdout is a terminal, in order to not break scripting. We could add a switch to force printing of context names too in case someone really wants it.

**Comment by TyBrown** [comment]
It looks like there's already a good example of checking for if it's a real tty/terminal already in [src/cmd/mod.rs L36](https://github.com/sbstp/kubie/blob/986101fdc05492a956ea16dca0e73545fc751762/src/cmd/mod.rs#L36), so I think this should be relatively easy to take a stab at. I'll start working on a PR tonight.
