### ISSUE TITLE
Request 32-bit ARM binary build

### ISSUE THREAD

**Issue by aboe76** [kubie-org/kubie#78]
I would like to have a 32-bit ARM binary for Raspberry Pi OS

**Comment by sbstp** [comment]
Hey, can you try the `kubie-linux-armv6` binary [here](https://github.com/sbstp/kubie/releases/tag/arm32-test-5)? I built it using armv6 w/o hardfloats so it should be compatible with every Pi back to the very first one! Let me know if you have issues.

**Comment by aboe76** [comment]
@sbstp will try thank you for your quick response.

**Comment by sbstp** [comment]
I did some testing on my end. The armv6/arm32 binary works well on my Raspberry Pi 400, but the arm64 binary does not. It turns out that even though the Raspberry Pi 400 has a armv8 CPU, the official kernel that is shipped is 32 bit. So I can't test the arm64 binary...

**Comment by aboe76** [comment]
@sbstp you could try the opensuse arm 64bit https://en.opensuse.org/openSUSE:AArch64

**Comment by sbstp** [comment]
Eh I think I will just leave it like that. The arm 32 bit build works fine, if someone tries the arm 64 build and it doesn't work I'll fix it then. You have the 32 bit build you wanted.

**Comment by aboe76** [comment]
@sbstp no problem, thank you for your work
